In [1]:
import pandas as pd

num = pd.read_csv(
    r"C:\Users\SARATH CHANDRA G\Downloads\2025q4\num.txt",
    sep="\t"
)

num.head()

C:\Users\SARATH CHANDRA G\AppData\Local\Temp\ipykernel_12788\2082932439.py:3: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  num = pd.read_csv(

,adsh,tag,version,ddate,qtrs,uom,segments,coreg,value,footnote
0,0000002488-25-000166,AccountsPayableCurrent,us-gaap/2025,20241231,0,USD,NaN,NaN,2.466000e+09,NaN
1,0000002488-25-000166,AccountsPayableCurrent,us-gaap/2025,20250930,0,USD,NaN,NaN,3.483000e+09,NaN
2,0000002488-25-000166,AccountsReceivableNetCurrent,us-gaap/2025,20241231,0,USD,NaN,NaN,6.192000e+09,NaN
3,0000002488-25-000166,AccountsReceivableNetCurrent,us-gaap/2025,20250930,0,USD,NaN,NaN,6.201000e+09,NaN
4,0000002488-25-000166,AccruedLiabilitiesCurrentAndNoncurrent,us-gaap/2025,20241231,0,USD,NaN,NaN,4.260000e+09,NaN

In [2]:
import pandas as pd

path = r"C:\Users\SARATH CHANDRA G\Downloads\2025q4"

num = pd.read_csv(path + r"\num.txt", sep="\t")
pre = pd.read_csv(path + r"\pre.txt", sep="\t")
sub = pd.read_csv(path + r"\sub.txt", sep="\t")
tag = pd.read_csv(path + r"\tag.txt", sep="\t")

print("NUM:", num.shape)
print("PRE:", pre.shape)
print("SUB:", sub.shape)
print("TAG:", tag.shape)

C:\Users\SARATH CHANDRA G\AppData\Local\Temp\ipykernel_12788\2168051114.py:5: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  num = pd.read_csv(path + r"\num.txt", sep="\t")

NUM: (3832977, 10)
PRE: (719346, 10)
SUB: (6304, 36)
TAG: (84907, 9)

In [3]:
print("\n========== SUB COLUMNS ==========")
print(sub.columns.tolist())

print("\n========== NUM COLUMNS ==========")
print(num.columns.tolist())

print("\n========== TAG COLUMNS ==========")
print(tag.columns.tolist())

========== SUB COLUMNS ==========
['adsh', 'cik', 'name', 'sic', 'countryba', 'stprba', 'cityba', 'zipba', 'bas1', 'bas2', 'baph', 'countryma', 'stprma', 'cityma', 'zipma', 'mas1', 'mas2', 'countryinc', 'stprinc', 'ein', 'former', 'changed', 'afs', 'wksi', 'fye', 'form', 'period', 'fy', 'fp', 'filed', 'accepted', 'prevrpt', 'detail', 'instance', 'nciks', 'aciks']

========== NUM COLUMNS ==========
['adsh', 'tag', 'version', 'ddate', 'qtrs', 'uom', 'segments', 'coreg', 'value', 'footnote']

========== TAG COLUMNS ==========
['tag', 'version', 'custom', 'abstract', 'datatype', 'iord', 'crdr', 'tlabel', 'doc']

In [4]:
display(sub.head())
display(num.head())
display(tag.head())

,adsh,cik,name,sic,countryba,stprba,cityba,zipba,bas1,bas2,...,period,fy,fp,filed,accepted,prevrpt,detail,instance,nciks,aciks
0,0000002488-25-000166,2488,ADVANCED MICRO DEVICES INC,3674.0,US,CA,SANTA CLARA,95054,2485 AUGUSTINE DRIVE,NaN,...,20250930,2025.0,Q3,20251105,2025-11-04 18:08:00.0,0,1,amd-20250927_htm.xml,1,NaN
1,0000002969-25-000055,2969,"AIR PRODUCTS & CHEMICALS, INC.",2810.0,US,PA,ALLENTOWN,18106-5500,1940 AIR PRODUCTS BLVD.,NaN,...,20250930,2025.0,FY,20251120,2025-11-20 10:21:00.0,0,1,apd-20250930_htm.xml,1,NaN
2,0000003499-25-000026,3499,ALEXANDERS INC,6798.0,US,NJ,PARAMUS,07652,210 ROUTE 4 EAST,NaN,...,20250930,2025.0,Q3,20251103,2025-11-03 08:42:00.0,0,1,alx-20250930_htm.xml,1,NaN
3,0000003545-25-000140,3545,"ALICO, INC.",100.0,US,FL,"FT. MYERS,",33913,10070 DANIELS INTERSTATE COURT STE. 100,NaN,...,20250930,2025.0,FY,20251124,2025-11-24 16:22:00.0,0,1,alco-20250930_htm.xml,1,NaN
4,0000003570-25-000107,3570,CHENIERE ENERGY INC,4924.0,US,TX,HOUSTON,77002,845 TEXAS AVENUE,SUITE 1250,...,20250930,2025.0,Q3,20251030,2025-10-29 17:36:00.0,0,1,lng-20250930_htm.xml,1,NaN

,adsh,tag,version,ddate,qtrs,uom,segments,coreg,value,footnote
0,0000002488-25-000166,AccountsPayableCurrent,us-gaap/2025,20241231,0,USD,NaN,NaN,2.466000e+09,NaN
1,0000002488-25-000166,AccountsPayableCurrent,us-gaap/2025,20250930,0,USD,NaN,NaN,3.483000e+09,NaN
2,0000002488-25-000166,AccountsReceivableNetCurrent,us-gaap/2025,20241231,0,USD,NaN,NaN,6.192000e+09,NaN
3,0000002488-25-000166,AccountsReceivableNetCurrent,us-gaap/2025,20250930,0,USD,NaN,NaN,6.201000e+09,NaN
4,0000002488-25-000166,AccruedLiabilitiesCurrentAndNoncurrent,us-gaap/2025,20241231,0,USD,NaN,NaN,4.260000e+09,NaN

,tag,version,custom,abstract,datatype,iord,crdr,tlabel,doc
0,AccountsPayableAndOtherAccruedLiabilities,us-gaap/2024,0,0,monetary,I,C,Accounts Payable and Other Accrued Liabilities,Amount of liabilities incurred and payable to ...
1,AccountsPayableTradeCurrent,us-gaap/2024,0,0,monetary,I,C,"Accounts Payable, Trade, Current",Carrying value as of the balance sheet date of...
2,AccruedIncomeTaxesNoncurrent,us-gaap/2024,0,0,monetary,I,C,"Accrued Income Taxes, Noncurrent",Carrying amount as of the balance sheet date o...
3,AccumulatedDeferredInvestmentTaxCredit,us-gaap/2024,0,0,monetary,I,C,Accumulated Deferred Investment Tax Credit,The noncurrent portion of the reserve for accu...
4,AccumulatedOtherComprehensiveIncomeLossDefined...,us-gaap/2024,0,0,monetary,I,D,"Accumulated Other Comprehensive (Income) Loss,...","Amount, after tax, of accumulated other compre..."

In [5]:
# ============================================================
# DATA CLEANING
# ============================================================

# Convert important columns
num["tag"] = num["tag"].astype(str).str.strip()
num["adsh"] = num["adsh"].astype(str).str.strip()
num["uom"] = num["uom"].astype(str).str.strip()

# Date conversion
num["ddate"] = pd.to_datetime(
    num["ddate"].astype(str),
    format="%Y%m%d",
    errors="coerce"
)

# Numeric conversion
num["value"] = pd.to_numeric(
    num["value"],
    errors="coerce"
)

# Quarter count
num["qtrs"] = pd.to_numeric(
    num["qtrs"],
    errors="coerce"
)

# Remove invalid records
num = num.dropna(
    subset=["adsh", "tag", "value"]
)

print("Cleaned NUM shape:", num.shape)

display(num.head())

Cleaned NUM shape: (3650589, 10)

,adsh,tag,version,ddate,qtrs,uom,segments,coreg,value,footnote
0,0000002488-25-000166,AccountsPayableCurrent,us-gaap/2025,2024-12-31,0,USD,NaN,NaN,2.466000e+09,NaN
1,0000002488-25-000166,AccountsPayableCurrent,us-gaap/2025,2025-09-30,0,USD,NaN,NaN,3.483000e+09,NaN
2,0000002488-25-000166,AccountsReceivableNetCurrent,us-gaap/2025,2024-12-31,0,USD,NaN,NaN,6.192000e+09,NaN
3,0000002488-25-000166,AccountsReceivableNetCurrent,us-gaap/2025,2025-09-30,0,USD,NaN,NaN,6.201000e+09,NaN
4,0000002488-25-000166,AccruedLiabilitiesCurrentAndNoncurrent,us-gaap/2025,2024-12-31,0,USD,NaN,NaN,4.260000e+09,NaN

In [6]:
# ============================================================
# CLEAN SUBMISSION DATA
# ============================================================

sub["adsh"] = sub["adsh"].astype(str).str.strip()

sub["name"] = (
    sub["name"]
    .astype(str)
    .str.strip()
)

sub["cik"] = (
    sub["cik"]
    .astype(str)
    .str.replace(".0", "", regex=False)
)

sub["form"] = (
    sub["form"]
    .astype(str)
    .str.strip()
)

sub["fp"] = (
    sub["fp"]
    .astype(str)
    .str.upper()
    .str.strip()
)

sub["filed"] = pd.to_datetime(
    sub["filed"],
    errors="coerce"
)

print("Cleaned SUB shape:", sub.shape)

display(
    sub[
        ["adsh", "cik", "name", "form", "fp", "filed"]
    ].head()
)

Cleaned SUB shape: (6304, 36)

,adsh,cik,name,form,fp,filed
0,0000002488-25-000166,2488,ADVANCED MICRO DEVICES INC,10-Q,Q3,1970-01-01 00:00:00.020251105
1,0000002969-25-000055,2969,"AIR PRODUCTS & CHEMICALS, INC.",10-K,FY,1970-01-01 00:00:00.020251120
2,0000003499-25-000026,3499,ALEXANDERS INC,10-Q,Q3,1970-01-01 00:00:00.020251103
3,0000003545-25-000140,3545,"ALICO, INC.",10-K,FY,1970-01-01 00:00:00.020251124
4,0000003570-25-000107,3570,CHENIERE ENERGY INC,10-Q,Q3,1970-01-01 00:00:00.020251030

In [7]:
# ============================================================
# MERGE NUMERICAL DATA WITH COMPANY INFORMATION
# ============================================================

company_info = sub[
    [
        "adsh",
        "cik",
        "name",
        "form",
        "fp",
        "filed"
    ]
].drop_duplicates("adsh")

financial = num.merge(
    company_info,
    on="adsh",
    how="left"
)

print("Merged financial dataset:")
print(financial.shape)

display(financial.head())

Merged financial dataset:
(3650589, 15)

,adsh,tag,version,ddate,qtrs,uom,segments,coreg,value,footnote,cik,name,form,fp,filed
0,0000002488-25-000166,AccountsPayableCurrent,us-gaap/2025,2024-12-31,0,USD,NaN,NaN,2.466000e+09,NaN,2488,ADVANCED MICRO DEVICES INC,10-Q,Q3,1970-01-01 00:00:00.020251105
1,0000002488-25-000166,AccountsPayableCurrent,us-gaap/2025,2025-09-30,0,USD,NaN,NaN,3.483000e+09,NaN,2488,ADVANCED MICRO DEVICES INC,10-Q,Q3,1970-01-01 00:00:00.020251105
2,0000002488-25-000166,AccountsReceivableNetCurrent,us-gaap/2025,2024-12-31,0,USD,NaN,NaN,6.192000e+09,NaN,2488,ADVANCED MICRO DEVICES INC,10-Q,Q3,1970-01-01 00:00:00.020251105
3,0000002488-25-000166,AccountsReceivableNetCurrent,us-gaap/2025,2025-09-30,0,USD,NaN,NaN,6.201000e+09,NaN,2488,ADVANCED MICRO DEVICES INC,10-Q,Q3,1970-01-01 00:00:00.020251105
4,0000002488-25-000166,AccruedLiabilitiesCurrentAndNoncurrent,us-gaap/2025,2024-12-31,0,USD,NaN,NaN,4.260000e+09,NaN,2488,ADVANCED MICRO DEVICES INC,10-Q,Q3,1970-01-01 00:00:00.020251105

In [8]:
# ============================================================
# TARGET COMPANIES
# ============================================================

TARGET_COMPANIES = [
    "Microsoft",
    "Alphabet",
    "Amazon",
    "NVIDIA",
    "Meta",
    "AMD",
    "Intel",
    "Salesforce",
    "IBM",
    "Cisco"
]

print(TARGET_COMPANIES)

['Microsoft', 'Alphabet', 'Amazon', 'NVIDIA', 'Meta', 'AMD', 'Intel', 'Salesforce', 'IBM', 'Cisco']

In [9]:
def company_match(name, keyword):
    return keyword.lower() in str(name).lower()


for company in TARGET_COMPANIES:

    matches = financial[
        financial["name"]
        .str.contains(
            company,
            case=False,
            na=False
        )
    ]

    print(
        company,
        "→",
        matches["name"].dropna().unique()[:5]
    )

Microsoft → ['MICROSOFT CORP']
Alphabet → ['ALPHABET INC.']
Amazon → ['AMAZON COM INC']
NVIDIA → ['NVIDIA CORP']
Meta → ['COMMERCIAL METALS CO' 'PLATINUM GROUP METALS LTD' 'TRILOGY METALS INC.'
 'METAVIA INC.' 'TMC THE METALS CO INC.']
AMD → ['CAMDEN NATIONAL CORP' 'AMDOCS LTD' 'CAMDEN PROPERTY TRUST']
Intel → ['INTEL CORP' 'INTELLICHECK, INC.'
 'CCC INTELLIGENT SOLUTIONS HOLDINGS INC.' 'INTELLIA THERAPEUTICS, INC.'
 'INTELLIGENT PROTECTION MANAGEMENT CORP.']
Salesforce → ['SALESFORCE, INC.']
IBM → []
Cisco → ['CISCO SYSTEMS, INC.' 'FEDERAL HOME LOAN BANK OF SAN FRANCISCO']

In [10]:
# ============================================================
# FILTER RELEVANT SEC FILINGS
# ============================================================

financial = financial[
    financial["form"].isin(
        ["10-K", "10-Q"]
    )
].copy()

print("Relevant filings:", financial.shape)

print(
    financial["form"]
    .value_counts()
)

Relevant filings: (3314841, 15)
form
10-Q    3090755
10-K     224086
Name: count, dtype: int64

In [11]:
# ============================================================
# FINANCIAL METRIC TAG DICTIONARY
# ============================================================

METRIC_TAGS = {

    "revenue": [
        "Revenue",
        "Revenues",
        "SalesRevenueNet",
        "SalesRevenueGoodsNet",
        "RevenueFromContractWithCustomerExcludingAssessedTax"
    ],

    "net_income": [
        "NetIncomeLoss",
        "ProfitLoss",
        "NetIncomeLossAvailableToCommonStockholdersBasic"
    ],

    "operating_income": [
        "OperatingIncomeLoss"
    ],

    "gross_profit": [
        "GrossProfit"
    ],

    "ebitda": [
        "EarningsBeforeInterestTaxesDepreciationAndAmortization"
    ],

    "assets": [
        "Assets"
    ],

    "liabilities": [
        "Liabilities"
    ],

    "equity": [
        "StockholdersEquity",
        "StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest"
    ],

    "cash": [
        "CashAndCashEquivalentsAtCarryingValue"
    ],

    "debt": [
        "LongTermDebt",
        "LongTermDebtCurrent",
        "LongTermDebtNoncurrent"
    ],

    "eps_basic": [
        "EarningsPerShareBasic"
    ],

    "eps_diluted": [
        "EarningsPerShareDiluted"
    ],

    "operating_cash_flow": [
        "NetCashProvidedByUsedInOperatingActivities"
    ],

    "capital_expenditure": [
        "PaymentsToAcquirePropertyPlantAndEquipment"
    ]
}

In [12]:
# ============================================================
# METRIC EXTRACTION FUNCTION
# ============================================================

def extract_metric(df, tag_list):

    pattern = "|".join(
        re.escape(tag)
        for tag in tag_list
    )

    result = df[
        df["tag"]
        .str.contains(
            pattern,
            case=False,
            regex=True,
            na=False
        )
    ].copy()

    return result

In [13]:
import re


revenue_df = extract_metric(
    financial,
    METRIC_TAGS["revenue"]
)

net_income_df = extract_metric(
    financial,
    METRIC_TAGS["net_income"]
)

operating_income_df = extract_metric(
    financial,
    METRIC_TAGS["operating_income"]
)

gross_profit_df = extract_metric(
    financial,
    METRIC_TAGS["gross_profit"]
)

assets_df = extract_metric(
    financial,
    METRIC_TAGS["assets"]
)

liabilities_df = extract_metric(
    financial,
    METRIC_TAGS["liabilities"]
)

cash_df = extract_metric(
    financial,
    METRIC_TAGS["cash"]
)

eps_df = extract_metric(
    financial,
    METRIC_TAGS["eps_diluted"]
)

ocf_df = extract_metric(
    financial,
    METRIC_TAGS["operating_cash_flow"]
)

In [14]:
print("Revenue:", revenue_df.shape)
print("Net Income:", net_income_df.shape)
print("Operating Income:", operating_income_df.shape)
print("Gross Profit:", gross_profit_df.shape)
print("Assets:", assets_df.shape)
print("Liabilities:", liabilities_df.shape)
print("Cash:", cash_df.shape)
print("EPS:", eps_df.shape)
print("Operating Cash Flow:", ocf_df.shape)

Revenue: (193886, 15)
Net Income: (112525, 15)
Operating Income: (30995, 15)
Gross Profit: (13041, 15)
Assets: (185154, 15)
Liabilities: (93941, 15)
Cash: (13712, 15)
EPS: (21638, 15)
Operating Cash Flow: (12522, 15)

In [15]:
print("Revenue tags:")
print(revenue_df["tag"].value_counts().head(20))

print("\nNet Income tags:")
print(net_income_df["tag"].value_counts().head(20))

print("\nEPS tags:")
print(eps_df["tag"].value_counts().head(20))

Revenue tags:
tag
RevenueFromContractWithCustomerExcludingAssessedTax    110362
Revenues                                                46302
RevenueFromContractWithCustomerIncludingAssessedTax     15579
CostOfRevenue                                           10187
IncreaseDecreaseInDeferredRevenue                        1040
DeferredRevenueCurrent                                    732
RevenuesNetOfInterestExpense                              663
RegulatedAndUnregulatedOperatingRevenue                   637
RevenueNotFromContractWithCustomer                        485
OtherCostOfOperatingRevenue                               344
DeferredRevenueNoncurrent                                 283
BrokerageCommissionsRevenue                               278
RegulatedOperatingRevenue                                 251
DeferredRevenue                                           176
InvestmentBankingRevenue                                  158
UnregulatedOperatingRevenue                               157
RegulatedOperatingRevenueGas                              145
RevenuesFromRelatedParties                                120
InterestRevenueExpenseNet                                 115
CostOfRevenues                                            106
Name: count, dtype: int64

Net Income tags:
tag
NetIncomeLoss                                                                            61857
ProfitLoss                                                                               29567
NetIncomeLossAttributableToNoncontrollingInterest                                         7108
NetIncomeLossAvailableToCommonStockholdersBasic                                           4421
NetIncomeLossIncludingPortionAttributableToNonredeemableNoncontrollingInterest            2343
NetIncomeLossAvailableToCommonStockholdersDiluted                                          804
NetIncomeLossAttributableToRedeemableNoncontrollingInterest                                742
NetIncomeLossAttributableToNonredeemableNoncontrollingInterest                             466
AdjustmentsToReconcileNetIncomeLossToCashProvidedByUsedInOperatingActivities               279
NetIncomeLossPerOutstandingLimitedPartnershipUnitBasicNetOfTax                             211
NetIncomeLossFromContinuingOperationsAvailableToCommonShareholdersBasic                    178
NetIncomeLossAllocatedToLimitedPartners                                                    171
NetIncomeLossNetOfTaxPerOutstandingLimitedPartnershipUnitDiluted                           152
NoncontrollingInterestInNetIncomeLossOperatingPartnershipsRedeemable                       131
NetIncomeLossAllocatedToGeneralPartners                                                    106
NetIncomeLossAvailableToCommonStockholders                                                  82
NetIncomeLossPerOutstandingLimitedPartnershipAndGeneralPartnershipUnitBasicAndDiluted       73
NetProfitLoss                                                                               67
NoncontrollingInterestInNetIncomeLossOtherNoncontrollingInterestsNonredeemable              65
ProfitLossFromRealEstateOperations                                                          63
Name: count, dtype: int64

EPS tags:
tag
EarningsPerShareDiluted                                                        21624
EarningsPerShareDilutedincludingportionattributabletononcontrollinginterest        4
EarningsPerShareDilutedUndistributed                                               4
EarningsPerShareDilutedNonRedeemableOrdinaryShares                                 4
EarningsPerShareDilutedNoncontrolling                                              2
Name: count, dtype: int64

In [16]:
print(
    revenue_df["name"]
    .value_counts()
    .head(30)
)

name
EXELON CORP                        836
JOHNSON & JOHNSON                  654
AGCO CORP /DE                      506
MERCK & CO., INC.                  468
MOODYS CORP /DE/                   462
SOUTHERN COPPER CORP/              442
ORGANON & CO.                      436
NEWMONT CORP /DE/                  432
AMERIPRISE FINANCIAL INC           428
COMPASS DIVERSIFIED HOLDINGS       420
ASHFORD HOSPITALITY TRUST INC      386
NIKE, INC.                         378
HYPERSCALE DATA, INC.              375
LIBERTY LATIN AMERICA LTD.         372
GILEAD SCIENCES, INC.              372
CDW CORP                           364
CBOE GLOBAL MARKETS, INC.          361
ACACIA RESEARCH CORP               357
HYATT HOTELS CORP                  356
INTERCONTINENTAL EXCHANGE, INC.    352
SKILLZ INC.                        349
RAYMOND JAMES FINANCIAL INC        345
SEI INVESTMENTS CO                 328
S&P GLOBAL INC.                    328
LOCKHEED MARTIN CORP               324
SIGNET JEWELERS LTD                320
BIOGEN INC.                        316
B. RILEY FINANCIAL, INC.           314
AMERICAN ELECTRIC POWER CO INC     303
MANPOWERGROUP INC.                 301
Name: count, dtype: int64

In [17]:
TARGET_COMPANIES = [
    "Microsoft",
    "Alphabet",
    "Amazon",
    "NVIDIA",
    "Meta",
    "AMD",
    "Intel",
    "Salesforce",
    "IBM",
    "Cisco"
]

for company in TARGET_COMPANIES:
    matches = revenue_df[
        revenue_df["name"]
        .str.contains(
            company,
            case=False,
            na=False
        )
    ]

    print(
        company,
        "→",
        matches["name"].unique()[:5]
    )

Microsoft → ['MICROSOFT CORP']
Alphabet → ['ALPHABET INC.']
Amazon → ['AMAZON COM INC']
NVIDIA → ['NVIDIA CORP']
Meta → ['COMMERCIAL METALS CO' 'METALLUS INC.' 'A-MARK PRECIOUS METALS, INC.'
 'METAGENOMI, INC.' 'LIQUIDMETAL TECHNOLOGIES INC']
AMD → ['CAMDEN NATIONAL CORP' 'CAMDEN PROPERTY TRUST']
Intel → ['INTEL CORP' 'INTELLICHECK, INC.'
 'CCC INTELLIGENT SOLUTIONS HOLDINGS INC.' 'INTELLIA THERAPEUTICS, INC.'
 'INTELLIGENT PROTECTION MANAGEMENT CORP.']
Salesforce → ['SALESFORCE, INC.']
IBM → []
Cisco → ['CISCO SYSTEMS, INC.']

In [18]:
print(
    revenue_df[
        ["ddate", "qtrs", "fp", "form", "filed"]
    ].head(30)
)

          ddate  qtrs  fp  form                         filed
301  2024-09-30     1  Q3  10-Q 1970-01-01 00:00:00.020251105
302  2024-09-30     1  Q3  10-Q 1970-01-01 00:00:00.020251105
303  2024-09-30     1  Q3  10-Q 1970-01-01 00:00:00.020251105
304  2024-09-30     1  Q3  10-Q 1970-01-01 00:00:00.020251105
305  2024-09-30     1  Q3  10-Q 1970-01-01 00:00:00.020251105
306  2024-09-30     1  Q3  10-Q 1970-01-01 00:00:00.020251105
307  2024-09-30     3  Q3  10-Q 1970-01-01 00:00:00.020251105
308  2024-09-30     3  Q3  10-Q 1970-01-01 00:00:00.020251105
309  2024-09-30     3  Q3  10-Q 1970-01-01 00:00:00.020251105
310  2024-09-30     3  Q3  10-Q 1970-01-01 00:00:00.020251105
311  2024-09-30     3  Q3  10-Q 1970-01-01 00:00:00.020251105
312  2024-09-30     3  Q3  10-Q 1970-01-01 00:00:00.020251105
313  2025-09-30     1  Q3  10-Q 1970-01-01 00:00:00.020251105
314  2025-09-30     1  Q3  10-Q 1970-01-01 00:00:00.020251105
315  2025-09-30     1  Q3  10-Q 1970-01-01 00:00:00.020251105
316  2025-09-30     1  Q3  10-Q 1970-01-01 00:00:00.020251105
317  2025-09-30     1  Q3  10-Q 1970-01-01 00:00:00.020251105
318  2025-09-30     1  Q3  10-Q 1970-01-01 00:00:00.020251105
319  2025-09-30     3  Q3  10-Q 1970-01-01 00:00:00.020251105
320  2025-09-30     3  Q3  10-Q 1970-01-01 00:00:00.020251105
321  2025-09-30     3  Q3  10-Q 1970-01-01 00:00:00.020251105
322  2025-09-30     3  Q3  10-Q 1970-01-01 00:00:00.020251105
323  2025-09-30     3  Q3  10-Q 1970-01-01 00:00:00.020251105
324  2025-09-30     3  Q3  10-Q 1970-01-01 00:00:00.020251105
1139 2023-09-30     4  FY  10-K 1970-01-01 00:00:00.020251120
1140 2023-09-30     4  FY  10-K 1970-01-01 00:00:00.020251120
1141 2023-09-30     4  FY  10-K 1970-01-01 00:00:00.020251120
1142 2023-09-30     4  FY  10-K 1970-01-01 00:00:00.020251120
1143 2023-09-30     4  FY  10-K 1970-01-01 00:00:00.020251120
1144 2023-09-30     4  FY  10-K 1970-01-01 00:00:00.020251120

In [19]:
print(
    revenue_df["qtrs"]
    .value_counts()
)

qtrs
1     92036
3     83482
4     11189
2      5373
0      1796
13        2
7         2
15        1
5         1
79        1
24        1
21        1
9         1
Name: count, dtype: int64

In [20]:
def prepare_metric(df, metric_name):
    result = df[
        [
            "adsh",
            "name",
            "cik",
            "tag",
            "ddate",
            "qtrs",
            "uom",
            "value",
            "form",
            "fp",
            "filed"
        ]
    ].copy()

    result["metric"] = metric_name

    return result

In [21]:
metrics_long = pd.concat([
    prepare_metric(revenue_df, "revenue"),
    prepare_metric(net_income_df, "net_income"),
    prepare_metric(operating_income_df, "operating_income"),
    prepare_metric(gross_profit_df, "gross_profit"),
    prepare_metric(assets_df, "assets"),
    prepare_metric(liabilities_df, "liabilities"),
    prepare_metric(cash_df, "cash"),
    prepare_metric(eps_df, "eps_diluted"),
    prepare_metric(ocf_df, "operating_cash_flow")
], ignore_index=True)

print(metrics_long.shape)

display(metrics_long.head(20))

(677414, 12)

,adsh,name,cik,tag,ddate,qtrs,uom,value,form,fp,filed,metric
0,0000002488-25-000166,ADVANCED MICRO DEVICES INC,2488,RevenueFromContractWithCustomerExcludingAssess...,2024-09-30,1,USD,6.819000e+09,10-Q,Q3,1970-01-01 00:00:00.020251105,revenue
1,0000002488-25-000166,ADVANCED MICRO DEVICES INC,2488,RevenueFromContractWithCustomerExcludingAssess...,2024-09-30,1,USD,2.343000e+09,10-Q,Q3,1970-01-01 00:00:00.020251105,revenue
2,0000002488-25-000166,ADVANCED MICRO DEVICES INC,2488,RevenueFromContractWithCustomerExcludingAssess...,2024-09-30,1,USD,1.881000e+09,10-Q,Q3,1970-01-01 00:00:00.020251105,revenue
3,0000002488-25-000166,ADVANCED MICRO DEVICES INC,2488,RevenueFromContractWithCustomerExcludingAssess...,2024-09-30,1,USD,4.620000e+08,10-Q,Q3,1970-01-01 00:00:00.020251105,revenue
4,0000002488-25-000166,ADVANCED MICRO DEVICES INC,2488,RevenueFromContractWithCustomerExcludingAssess...,2024-09-30,1,USD,3.549000e+09,10-Q,Q3,1970-01-01 00:00:00.020251105,revenue
5,0000002488-25-000166,ADVANCED MICRO DEVICES INC,2488,RevenueFromContractWithCustomerExcludingAssess...,2024-09-30,1,USD,9.270000e+08,10-Q,Q3,1970-01-01 00:00:00.020251105,revenue
6,0000002488-25-000166,ADVANCED MICRO DEVICES INC,2488,RevenueFromContractWithCustomerExcludingAssess...,2024-09-30,3,USD,1.812700e+10,10-Q,Q3,1970-01-01 00:00:00.020251105,revenue
7,0000002488-25-000166,ADVANCED MICRO DEVICES INC,2488,RevenueFromContractWithCustomerExcludingAssess...,2024-09-30,3,USD,6.773000e+09,10-Q,Q3,1970-01-01 00:00:00.020251105,revenue
8,0000002488-25-000166,ADVANCED MICRO DEVICES INC,2488,RevenueFromContractWithCustomerExcludingAssess...,2024-09-30,3,USD,4.741000e+09,10-Q,Q3,1970-01-01 00:00:00.020251105,revenue
9,0000002488-25-000166,ADVANCED MICRO DEVICES INC,2488,RevenueFromContractWithCustomerExcludingAssess...,2024-09-30,3,USD,2.032000e+09,10-Q,Q3,1970-01-01 00:00:00.020251105,revenue
10,0000002488-25-000166,ADVANCED MICRO DEVICES INC,2488,RevenueFromContractWithCustomerExcludingAssess...,2024-09-30,3,USD,8.720000e+09,10-Q,Q3,1970-01-01 00:00:00.020251105,revenue
11,0000002488-25-000166,ADVANCED MICRO DEVICES INC,2488,RevenueFromContractWithCustomerExcludingAssess...,2024-09-30,3,USD,2.634000e+09,10-Q,Q3,1970-01-01 00:00:00.020251105,revenue
12,0000002488-25-000166,ADVANCED MICRO DEVICES INC,2488,RevenueFromContractWithCustomerExcludingAssess...,2025-09-30,1,USD,9.246000e+09,10-Q,Q3,1970-01-01 00:00:00.020251105,revenue
13,0000002488-25-000166,ADVANCED MICRO DEVICES INC,2488,RevenueFromContractWithCustomerExcludingAssess...,2025-09-30,1,USD,4.048000e+09,10-Q,Q3,1970-01-01 00:00:00.020251105,revenue
14,0000002488-25-000166,ADVANCED MICRO DEVICES INC,2488,RevenueFromContractWithCustomerExcludingAssess...,2025-09-30,1,USD,2.750000e+09,10-Q,Q3,1970-01-01 00:00:00.020251105,revenue
15,0000002488-25-000166,ADVANCED MICRO DEVICES INC,2488,RevenueFromContractWithCustomerExcludingAssess...,2025-09-30,1,USD,1.298000e+09,10-Q,Q3,1970-01-01 00:00:00.020251105,revenue
16,0000002488-25-000166,ADVANCED MICRO DEVICES INC,2488,RevenueFromContractWithCustomerExcludingAssess...,2025-09-30,1,USD,4.341000e+09,10-Q,Q3,1970-01-01 00:00:00.020251105,revenue
17,0000002488-25-000166,ADVANCED MICRO DEVICES INC,2488,RevenueFromContractWithCustomerExcludingAssess...,2025-09-30,1,USD,8.570000e+08,10-Q,Q3,1970-01-01 00:00:00.020251105,revenue
18,0000002488-25-000166,ADVANCED MICRO DEVICES INC,2488,RevenueFromContractWithCustomerExcludingAssess...,2025-09-30,3,USD,2.436900e+10,10-Q,Q3,1970-01-01 00:00:00.020251105,revenue
19,0000002488-25-000166,ADVANCED MICRO DEVICES INC,2488,RevenueFromContractWithCustomerExcludingAssess...,2025-09-30,3,USD,1.061000e+10,10-Q,Q3,1970-01-01 00:00:00.020251105,revenue

In [22]:
metrics_long.shape

(677414, 12)

In [23]:
display(
    metrics_long[
        [
            "name",
            "metric",
            "ddate",
            "qtrs",
            "uom",
            "value"
        ]
    ].head(20)
)

                          name   metric      ddate  qtrs  uom         value
0   ADVANCED MICRO DEVICES INC  revenue 2024-09-30     1  USD  6.819000e+09
1   ADVANCED MICRO DEVICES INC  revenue 2024-09-30     1  USD  2.343000e+09
2   ADVANCED MICRO DEVICES INC  revenue 2024-09-30     1  USD  1.881000e+09
3   ADVANCED MICRO DEVICES INC  revenue 2024-09-30     1  USD  4.620000e+08
4   ADVANCED MICRO DEVICES INC  revenue 2024-09-30     1  USD  3.549000e+09
5   ADVANCED MICRO DEVICES INC  revenue 2024-09-30     1  USD  9.270000e+08
6   ADVANCED MICRO DEVICES INC  revenue 2024-09-30     3  USD  1.812700e+10
7   ADVANCED MICRO DEVICES INC  revenue 2024-09-30     3  USD  6.773000e+09
8   ADVANCED MICRO DEVICES INC  revenue 2024-09-30     3  USD  4.741000e+09
9   ADVANCED MICRO DEVICES INC  revenue 2024-09-30     3  USD  2.032000e+09
10  ADVANCED MICRO DEVICES INC  revenue 2024-09-30     3  USD  8.720000e+09
11  ADVANCED MICRO DEVICES INC  revenue 2024-09-30     3  USD  2.634000e+09
12  ADVANCED MICRO DEVICES INC  revenue 2025-09-30     1  USD  9.246000e+09
13  ADVANCED MICRO DEVICES INC  revenue 2025-09-30     1  USD  4.048000e+09
14  ADVANCED MICRO DEVICES INC  revenue 2025-09-30     1  USD  2.750000e+09
15  ADVANCED MICRO DEVICES INC  revenue 2025-09-30     1  USD  1.298000e+09
16  ADVANCED MICRO DEVICES INC  revenue 2025-09-30     1  USD  4.341000e+09
17  ADVANCED MICRO DEVICES INC  revenue 2025-09-30     1  USD  8.570000e+08
18  ADVANCED MICRO DEVICES INC  revenue 2025-09-30     3  USD  2.436900e+10
19  ADVANCED MICRO DEVICES INC  revenue 2025-09-30     3  USD  1.061000e+10

In [24]:
def normalize_value(row):

    value = row["value"]
    unit = str(row["uom"]).upper()

    if pd.isna(value):
        return np.nan

    # EPS should remain unchanged
    if "SHARE" in unit:
        return value

    # Convert large monetary values to millions
    if unit == "USD":
        return value / 1_000_000

    return value


metrics_long["value_normalized"] = (
    metrics_long.apply(
        normalize_value,
        axis=1
    )
)

In [25]:
display(
    metrics_long[
        [
            "name",
            "metric",
            "uom",
            "value",
            "value_normalized"
        ]
    ].head(20)
)

                          name   metric  uom         value  value_normalized
0   ADVANCED MICRO DEVICES INC  revenue  USD  6.819000e+09            6819.0
1   ADVANCED MICRO DEVICES INC  revenue  USD  2.343000e+09            2343.0
2   ADVANCED MICRO DEVICES INC  revenue  USD  1.881000e+09            1881.0
3   ADVANCED MICRO DEVICES INC  revenue  USD  4.620000e+08             462.0
4   ADVANCED MICRO DEVICES INC  revenue  USD  3.549000e+09            3549.0
5   ADVANCED MICRO DEVICES INC  revenue  USD  9.270000e+08             927.0
6   ADVANCED MICRO DEVICES INC  revenue  USD  1.812700e+10           18127.0
7   ADVANCED MICRO DEVICES INC  revenue  USD  6.773000e+09            6773.0
8   ADVANCED MICRO DEVICES INC  revenue  USD  4.741000e+09            4741.0
9   ADVANCED MICRO DEVICES INC  revenue  USD  2.032000e+09            2032.0
10  ADVANCED MICRO DEVICES INC  revenue  USD  8.720000e+09            8720.0
11  ADVANCED MICRO DEVICES INC  revenue  USD  2.634000e+09            2634.0
12  ADVANCED MICRO DEVICES INC  revenue  USD  9.246000e+09            9246.0
13  ADVANCED MICRO DEVICES INC  revenue  USD  4.048000e+09            4048.0
14  ADVANCED MICRO DEVICES INC  revenue  USD  2.750000e+09            2750.0
15  ADVANCED MICRO DEVICES INC  revenue  USD  1.298000e+09            1298.0
16  ADVANCED MICRO DEVICES INC  revenue  USD  4.341000e+09            4341.0
17  ADVANCED MICRO DEVICES INC  revenue  USD  8.570000e+08             857.0
18  ADVANCED MICRO DEVICES INC  revenue  USD  2.436900e+10           24369.0
19  ADVANCED MICRO DEVICES INC  revenue  USD  1.061000e+10           10610.0

In [26]:
# Create year from the SEC date column
metrics_long["ddate"] = pd.to_datetime(
    metrics_long["ddate"],
    errors="coerce"
)

metrics_long["year"] = metrics_long["ddate"].dt.year

print(metrics_long[["ddate", "year"]].head(10))

       ddate    year
0 2024-09-30  2024.0
1 2024-09-30  2024.0
2 2024-09-30  2024.0
3 2024-09-30  2024.0
4 2024-09-30  2024.0
5 2024-09-30  2024.0
6 2024-09-30  2024.0
7 2024-09-30  2024.0
8 2024-09-30  2024.0
9 2024-09-30  2024.0

In [27]:
financial_wide = (
    metrics_long
    .pivot_table(
        index=["name", "year"],
        columns="metric",
        values="value_normalized",
        aggfunc="first"
    )
    .reset_index()
)

financial_wide.columns.name = None

print("Shape:", financial_wide.shape)

display(financial_wide.head(20))

Shape: (11515, 11)

,name,year,assets,cash,eps_diluted,gross_profit,liabilities,net_income,operating_cash_flow,operating_income,revenue
0,1 800 FLOWERS COM INC,2024.0,29.237000,NaN,-5.300000e-07,92.319,-8.806000,-34.190000,-177.241000,-46.981000,242.090000
1,1 800 FLOWERS COM INC,2025.0,772.617000,46.502000,-8.300000e-07,76.762,109.887000,-52.957000,-138.974000,-50.513000,215.200000
2,"10X GENOMICS, INC.",2024.0,918.636000,NaN,-3.000000e-07,106.393,41.165000,-59.949000,13.412000,-41.485000,45.261000
3,"10X GENOMICS, INC.",2025.0,1027.361000,NaN,-2.200000e-07,100.307,35.766000,-34.358000,95.273000,-32.242000,48.695000
4,1606 CORP.,2024.0,0.010140,NaN,-7.000000e-08,0.000,0.499231,-3.569636,-0.710699,-3.246179,0.000000
5,1606 CORP.,2025.0,0.014602,NaN,0.000000e+00,0.000,0.604106,-0.384516,-0.349281,-0.111446,0.000000
6,1847 HOLDINGS LLC,2024.0,33.647738,2.457086,1.680000e-05,NaN,5.853307,2.813784,-9.478950,-3.280309,1.425247
7,1847 HOLDINGS LLC,2025.0,35.911825,2.189759,9.000000e-08,NaN,13.098911,32.280122,2.990872,2.628258,6.897848
8,1RT ACQUISITION CORP.,2024.0,0.143423,NaN,NaN,NaN,0.138355,NaN,NaN,NaN,NaN
9,1RT ACQUISITION CORP.,2025.0,175.113471,0.741229,7.000000e-08,NaN,0.204278,-0.031000,-0.293043,-0.285197,NaN
10,1ST FRANKLIN FINANCIAL CORP,2024.0,391.000000,11.000000,5.200000e-07,NaN,1.446036,0.087694,63.344369,NaN,13.029391
11,1ST FRANKLIN FINANCIAL CORP,2025.0,1409.313986,37.855983,3.638000e-05,NaN,1.623781,6.185135,100.524468,NaN,14.490444
12,1ST SOURCE CORP,2024.0,8931.938000,NaN,1.410000e-06,NaN,24.106000,-0.023000,160.308000,NaN,4.598000
13,1ST SOURCE CORP,2025.0,9056.691000,NaN,1.710000e-06,NaN,39.053000,-0.017000,167.692000,NaN,4.530000
14,"1STDIBS.COM, INC.",2024.0,145.758000,22.018000,-1.500000e-07,15.036,11.475000,-5.683000,-5.708000,-7.392000,21.190000
15,"1STDIBS.COM, INC.",2025.0,135.201000,19.938000,-1.000000e-07,16.331,11.482000,-3.506000,-6.707000,-4.683000,21.972000
16,21SHARES ETHEREUM ETF,2024.0,16.869879,NaN,NaN,NaN,NaN,-3.223608,NaN,NaN,NaN
17,21SHARES ETHEREUM ETF,2025.0,45.916365,NaN,NaN,NaN,0.001661,16.956542,NaN,NaN,NaN
18,21SHARES SOLANA ETF,2025.0,0.500104,NaN,NaN,NaN,0.500004,NaN,NaN,NaN,NaN
19,"22ND CENTURY GROUP, INC.",2024.0,21.673000,4.422000,-1.760260e-03,-0.588,1.021000,-5.739000,-9.947000,-3.377000,3.102000

In [28]:
# ============================================
# FINANCIAL RATIO ANALYSIS
# ============================================
import pandas as pd
import numpy as np
def safe_divide(a, b):
    return np.where(
        (b != 0) & (~pd.isna(b)),
        a / b,
        np.nan
    )


# Net Profit Margin
if "net_income" in financial_wide.columns and "revenue" in financial_wide.columns:
    financial_wide["net_profit_margin"] = (
        safe_divide(
            financial_wide["net_income"],
            financial_wide["revenue"]
        ) * 100
    )


# Operating Margin
if "operating_income" in financial_wide.columns and "revenue" in financial_wide.columns:
    financial_wide["operating_margin"] = (
        safe_divide(
            financial_wide["operating_income"],
            financial_wide["revenue"]
        ) * 100
    )


# Gross Margin
if "gross_profit" in financial_wide.columns and "revenue" in financial_wide.columns:
    financial_wide["gross_margin"] = (
        safe_divide(
            financial_wide["gross_profit"],
            financial_wide["revenue"]
        ) * 100
    )


# Liability / Asset Ratio
if "liabilities" in financial_wide.columns and "assets" in financial_wide.columns:
    financial_wide["liability_asset_ratio"] = (
        safe_divide(
            financial_wide["liabilities"],
            financial_wide["assets"]
        )
    )


# Cash / Asset Ratio
if "cash" in financial_wide.columns and "assets" in financial_wide.columns:
    financial_wide["cash_asset_ratio"] = (
        safe_divide(
            financial_wide["cash"],
            financial_wide["assets"]
        )
    )


display(financial_wide.head(10))

,name,year,assets,cash,eps_diluted,gross_profit,liabilities,net_income,operating_cash_flow,operating_income,revenue,net_profit_margin,operating_margin,gross_margin,liability_asset_ratio,cash_asset_ratio
0,1 800 FLOWERS COM INC,2024.0,29.237000,NaN,-5.300000e-07,92.319,-8.806000,-34.190000,-177.241000,-46.981000,242.090000,-14.122847,-19.406419,38.134165,-0.301194,NaN
1,1 800 FLOWERS COM INC,2025.0,772.617000,46.502000,-8.300000e-07,76.762,109.887000,-52.957000,-138.974000,-50.513000,215.200000,-24.608271,-23.472584,35.670074,0.142227,0.060188
2,"10X GENOMICS, INC.",2024.0,918.636000,NaN,-3.000000e-07,106.393,41.165000,-59.949000,13.412000,-41.485000,45.261000,-132.451780,-91.657277,235.065509,0.044811,NaN
3,"10X GENOMICS, INC.",2025.0,1027.361000,NaN,-2.200000e-07,100.307,35.766000,-34.358000,95.273000,-32.242000,48.695000,-70.557552,-66.212137,205.990348,0.034813,NaN
4,1606 CORP.,2024.0,0.010140,NaN,-7.000000e-08,0.000,0.499231,-3.569636,-0.710699,-3.246179,0.000000,NaN,NaN,NaN,49.233826,NaN
5,1606 CORP.,2025.0,0.014602,NaN,0.000000e+00,0.000,0.604106,-0.384516,-0.349281,-0.111446,0.000000,NaN,NaN,NaN,41.371456,NaN
6,1847 HOLDINGS LLC,2024.0,33.647738,2.457086,1.680000e-05,NaN,5.853307,2.813784,-9.478950,-3.280309,1.425247,197.424306,-230.157229,NaN,0.173958,0.073024
7,1847 HOLDINGS LLC,2025.0,35.911825,2.189759,9.000000e-08,NaN,13.098911,32.280122,2.990872,2.628258,6.897848,467.973809,38.102579,NaN,0.364752,0.060976
8,1RT ACQUISITION CORP.,2024.0,0.143423,NaN,NaN,NaN,0.138355,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.964664,NaN
9,1RT ACQUISITION CORP.,2025.0,175.113471,0.741229,7.000000e-08,NaN,0.204278,-0.031000,-0.293043,-0.285197,NaN,NaN,NaN,NaN,0.001167,0.004233

In [29]:
# ============================================
# FINANCIAL RATIO ANALYSIS
# ============================================

def safe_divide(a, b):
    return np.where(
        (b != 0) & (~pd.isna(b)),
        a / b,
        np.nan
    )


# 1. Net Profit Margin
if "net_income" in financial_wide.columns and "revenue" in financial_wide.columns:
    financial_wide["net_profit_margin"] = (
        safe_divide(
            financial_wide["net_income"],
            financial_wide["revenue"]
        ) * 100
    )


# 2. Operating Margin
if "operating_income" in financial_wide.columns and "revenue" in financial_wide.columns:
    financial_wide["operating_margin"] = (
        safe_divide(
            financial_wide["operating_income"],
            financial_wide["revenue"]
        ) * 100
    )


# 3. Gross Margin
if "gross_profit" in financial_wide.columns and "revenue" in financial_wide.columns:
    financial_wide["gross_margin"] = (
        safe_divide(
            financial_wide["gross_profit"],
            financial_wide["revenue"]
        ) * 100
    )


# 4. Liability-to-Asset Ratio
if "liabilities" in financial_wide.columns and "assets" in financial_wide.columns:
    financial_wide["liability_asset_ratio"] = (
        safe_divide(
            financial_wide["liabilities"],
            financial_wide["assets"]
        )
    )


# 5. Cash-to-Asset Ratio
if "cash" in financial_wide.columns and "assets" in financial_wide.columns:
    financial_wide["cash_asset_ratio"] = (
        safe_divide(
            financial_wide["cash"],
            financial_wide["assets"]
        )
    )


display(financial_wide.head(10))

,name,year,assets,cash,eps_diluted,gross_profit,liabilities,net_income,operating_cash_flow,operating_income,revenue,net_profit_margin,operating_margin,gross_margin,liability_asset_ratio,cash_asset_ratio
0,1 800 FLOWERS COM INC,2024.0,29.237000,NaN,-5.300000e-07,92.319,-8.806000,-34.190000,-177.241000,-46.981000,242.090000,-14.122847,-19.406419,38.134165,-0.301194,NaN
1,1 800 FLOWERS COM INC,2025.0,772.617000,46.502000,-8.300000e-07,76.762,109.887000,-52.957000,-138.974000,-50.513000,215.200000,-24.608271,-23.472584,35.670074,0.142227,0.060188
2,"10X GENOMICS, INC.",2024.0,918.636000,NaN,-3.000000e-07,106.393,41.165000,-59.949000,13.412000,-41.485000,45.261000,-132.451780,-91.657277,235.065509,0.044811,NaN
3,"10X GENOMICS, INC.",2025.0,1027.361000,NaN,-2.200000e-07,100.307,35.766000,-34.358000,95.273000,-32.242000,48.695000,-70.557552,-66.212137,205.990348,0.034813,NaN
4,1606 CORP.,2024.0,0.010140,NaN,-7.000000e-08,0.000,0.499231,-3.569636,-0.710699,-3.246179,0.000000,NaN,NaN,NaN,49.233826,NaN
5,1606 CORP.,2025.0,0.014602,NaN,0.000000e+00,0.000,0.604106,-0.384516,-0.349281,-0.111446,0.000000,NaN,NaN,NaN,41.371456,NaN
6,1847 HOLDINGS LLC,2024.0,33.647738,2.457086,1.680000e-05,NaN,5.853307,2.813784,-9.478950,-3.280309,1.425247,197.424306,-230.157229,NaN,0.173958,0.073024
7,1847 HOLDINGS LLC,2025.0,35.911825,2.189759,9.000000e-08,NaN,13.098911,32.280122,2.990872,2.628258,6.897848,467.973809,38.102579,NaN,0.364752,0.060976
8,1RT ACQUISITION CORP.,2024.0,0.143423,NaN,NaN,NaN,0.138355,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.964664,NaN
9,1RT ACQUISITION CORP.,2025.0,175.113471,0.741229,7.000000e-08,NaN,0.204278,-0.031000,-0.293043,-0.285197,NaN,NaN,NaN,NaN,0.001167,0.004233

In [30]:
# ============================================
# FINANCIAL TREND ANALYSIS
# ============================================

# Sort by company and year
financial_wide = financial_wide.sort_values(
    ["name", "year"]
).reset_index(drop=True)


# Metrics for trend analysis
trend_metrics = [
    "revenue",
    "net_income",
    "operating_income",
    "gross_profit",
    "assets",
    "liabilities",
    "cash",
    "eps_diluted"
]


# Calculate year-over-year growth
for metric in trend_metrics:

    if metric in financial_wide.columns:

        financial_wide[f"{metric}_growth_pct"] = (
            financial_wide
            .groupby("name")[metric]
            .pct_change() * 100
        )


# Display trend columns
trend_columns = [
    "name",
    "year"
]

for metric in trend_metrics:
    if f"{metric}_growth_pct" in financial_wide.columns:
        trend_columns.append(f"{metric}_growth_pct")


display(financial_wide[trend_columns].head(20))

C:\Users\SARATH CHANDRA G\AppData\Local\Temp\ipykernel_12788\438257109.py:32: FutureWarning: The default fill_method='ffill' in SeriesGroupBy.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  .pct_change() * 100
C:\Users\SARATH CHANDRA G\AppData\Local\Temp\ipykernel_12788\438257109.py:32: FutureWarning: The default fill_method='ffill' in SeriesGroupBy.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  .pct_change() * 100
C:\Users\SARATH CHANDRA G\AppData\Local\Temp\ipykernel_12788\438257109.py:32: FutureWarning: The default fill_method='ffill' in SeriesGroupBy.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  .pct_change() * 100
C:\Users\SARATH CHANDRA G\AppData\Local\Temp\ipykernel_12788\438257109.py:32: FutureWarning: The default fill_method='ffill' in SeriesGroupBy.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  .pct_change() * 100
C:\Users\SARATH CHANDRA G\AppData\Local\Temp\ipykernel_12788\438257109.py:32: FutureWarning: The default fill_method='ffill' in SeriesGroupBy.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  .pct_change() * 100
C:\Users\SARATH CHANDRA G\AppData\Local\Temp\ipykernel_12788\438257109.py:32: FutureWarning: The default fill_method='ffill' in SeriesGroupBy.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  .pct_change() * 100
C:\Users\SARATH CHANDRA G\AppData\Local\Temp\ipykernel_12788\438257109.py:32: FutureWarning: The default fill_method='ffill' in SeriesGroupBy.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  .pct_change() * 100
C:\Users\SARATH CHANDRA G\AppData\Local\Temp\ipykernel_12788\438257109.py:32: FutureWarning: The default fill_method='ffill' in SeriesGroupBy.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  .pct_change() * 100

,name,year,revenue_growth_pct,net_income_growth_pct,operating_income_growth_pct,gross_profit_growth_pct,assets_growth_pct,liabilities_growth_pct,cash_growth_pct,eps_diluted_growth_pct
0,1 800 FLOWERS COM INC,2024.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1 800 FLOWERS COM INC,2025.0,-11.107439,54.890319,7.517933,-16.851352,2542.600130,-1347.865092,NaN,56.603774
2,"10X GENOMICS, INC.",2024.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"10X GENOMICS, INC.",2025.0,7.587106,-42.687951,-22.280342,-5.720301,11.835482,-13.115511,NaN,-26.666667
4,1606 CORP.,2024.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1606 CORP.,2025.0,NaN,-89.228145,-96.566856,NaN,44.003945,21.007309,NaN,-100.000000
6,1847 HOLDINGS LLC,2024.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1847 HOLDINGS LLC,2025.0,383.975620,1047.213930,-180.122269,NaN,6.728794,123.786502,-10.879839,-99.464286
8,1RT ACQUISITION CORP.,2024.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1RT ACQUISITION CORP.,2025.0,NaN,NaN,NaN,NaN,121995.808204,47.647718,NaN,NaN
10,1ST FRANKLIN FINANCIAL CORP,2024.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1ST FRANKLIN FINANCIAL CORP,2025.0,11.213517,6953.088011,NaN,NaN,260.438360,12.291879,244.145300,6896.153846
12,1ST SOURCE CORP,2024.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1ST SOURCE CORP,2025.0,-1.478904,-26.086957,NaN,NaN,1.396707,62.005310,NaN,21.276596
14,"1STDIBS.COM, INC.",2024.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,"1STDIBS.COM, INC.",2025.0,3.690420,-38.307232,-36.647727,8.612663,-7.242827,0.061002,-9.446816,-33.333333
16,21SHARES ETHEREUM ETF,2024.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,21SHARES ETHEREUM ETF,2025.0,NaN,-626.011289,NaN,NaN,172.179575,NaN,NaN,NaN
18,21SHARES SOLANA ETF,2025.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,"22ND CENTURY GROUP, INC.",2024.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
# ============================================
# FINANCIAL HEALTH SCORE
# ============================================

def calculate_health_score(row):

    score = 100

    # Profitability
    if "net_profit_margin" in row and pd.notna(row["net_profit_margin"]):
        if row["net_profit_margin"] < 0:
            score -= 25
        elif row["net_profit_margin"] < 5:
            score -= 10

    # Revenue growth
    if "revenue_growth_pct" in row and pd.notna(row["revenue_growth_pct"]):
        if row["revenue_growth_pct"] < 0:
            score -= 20

    # Net income growth
    if "net_income_growth_pct" in row and pd.notna(row["net_income_growth_pct"]):
        if row["net_income_growth_pct"] < 0:
            score -= 20

    # EPS growth
    if "eps_diluted_growth_pct" in row and pd.notna(row["eps_diluted_growth_pct"]):
        if row["eps_diluted_growth_pct"] < 0:
            score -= 15

    # Liability / asset ratio
    if "liability_asset_ratio" in row and pd.notna(row["liability_asset_ratio"]):
        if row["liability_asset_ratio"] > 0.75:
            score -= 15
        elif row["liability_asset_ratio"] > 0.60:
            score -= 5

    # Keep score between 0 and 100
    return max(0, min(100, score))


financial_wide["financial_health_score"] = (
    financial_wide.apply(calculate_health_score, axis=1)
)


# Health category
def health_category(score):

    if score >= 80:
        return "Strong"

    elif score >= 60:
        return "Moderate"

    elif score >= 40:
        return "Weak"

    else:
        return "Critical"


financial_wide["financial_health"] = (
    financial_wide["financial_health_score"]
    .apply(health_category)
)


display(
    financial_wide[
        [
            "name",
            "year",
            "financial_health_score",
            "financial_health"
        ]
    ].head(20)
)

,name,year,financial_health_score,financial_health
0,1 800 FLOWERS COM INC,2024.0,75,Moderate
1,1 800 FLOWERS COM INC,2025.0,55,Weak
2,"10X GENOMICS, INC.",2024.0,75,Moderate
3,"10X GENOMICS, INC.",2025.0,40,Weak
4,1606 CORP.,2024.0,85,Strong
5,1606 CORP.,2025.0,50,Weak
6,1847 HOLDINGS LLC,2024.0,100,Strong
7,1847 HOLDINGS LLC,2025.0,85,Strong
8,1RT ACQUISITION CORP.,2024.0,85,Strong
9,1RT ACQUISITION CORP.,2025.0,100,Strong
10,1ST FRANKLIN FINANCIAL CORP,2024.0,90,Strong
11,1ST FRANKLIN FINANCIAL CORP,2025.0,100,Strong
12,1ST SOURCE CORP,2024.0,75,Moderate
13,1ST SOURCE CORP,2025.0,35,Critical
14,"1STDIBS.COM, INC.",2024.0,75,Moderate
15,"1STDIBS.COM, INC.",2025.0,40,Weak
16,21SHARES ETHEREUM ETF,2024.0,100,Strong
17,21SHARES ETHEREUM ETF,2025.0,80,Strong
18,21SHARES SOLANA ETF,2025.0,85,Strong
19,"22ND CENTURY GROUP, INC.",2024.0,75,Moderate

In [32]:
# ============================================
# FINANCIAL RISK DETECTION
# ============================================

def detect_risks(row):

    risks = []

    if row.get("revenue_growth_pct", 0) < 0:
        risks.append("Revenue Decline")

    if row.get("net_income_growth_pct", 0) < 0:
        risks.append("Net Income Decline")

    if row.get("eps_diluted_growth_pct", 0) < 0:
        risks.append("EPS Decline")

    if row.get("net_profit_margin", 100) < 5:
        risks.append("Low Profitability")

    if row.get("liability_asset_ratio", 0) > 0.75:
        risks.append("High Financial Leverage")

    if row.get("cash_asset_ratio", 1) < 0.05:
        risks.append("Low Cash Position")

    if len(risks) == 0:
        return "No Major Risk"

    return ", ".join(risks)


financial_wide["risk_flags"] = (
    financial_wide.apply(detect_risks, axis=1)
)


display(
    financial_wide[
        [
            "name",
            "year",
            "financial_health_score",
            "financial_health",
            "risk_flags"
        ]
    ].head(20)
)

,name,year,financial_health_score,financial_health,risk_flags
0,1 800 FLOWERS COM INC,2024.0,75,Moderate,Low Profitability
1,1 800 FLOWERS COM INC,2025.0,55,Weak,"Revenue Decline, Low Profitability"
2,"10X GENOMICS, INC.",2024.0,75,Moderate,Low Profitability
3,"10X GENOMICS, INC.",2025.0,40,Weak,"Net Income Decline, EPS Decline, Low Profitabi..."
4,1606 CORP.,2024.0,85,Strong,High Financial Leverage
5,1606 CORP.,2025.0,50,Weak,"Net Income Decline, EPS Decline, High Financia..."
6,1847 HOLDINGS LLC,2024.0,100,Strong,No Major Risk
7,1847 HOLDINGS LLC,2025.0,85,Strong,EPS Decline
8,1RT ACQUISITION CORP.,2024.0,85,Strong,High Financial Leverage
9,1RT ACQUISITION CORP.,2025.0,100,Strong,Low Cash Position
10,1ST FRANKLIN FINANCIAL CORP,2024.0,90,Strong,"Low Profitability, Low Cash Position"
11,1ST FRANKLIN FINANCIAL CORP,2025.0,100,Strong,Low Cash Position
12,1ST SOURCE CORP,2024.0,75,Moderate,Low Profitability
13,1ST SOURCE CORP,2025.0,35,Critical,"Revenue Decline, Net Income Decline, Low Profi..."
14,"1STDIBS.COM, INC.",2024.0,75,Moderate,Low Profitability
15,"1STDIBS.COM, INC.",2025.0,40,Weak,"Net Income Decline, EPS Decline, Low Profitabi..."
16,21SHARES ETHEREUM ETF,2024.0,100,Strong,No Major Risk
17,21SHARES ETHEREUM ETF,2025.0,80,Strong,Net Income Decline
18,21SHARES SOLANA ETF,2025.0,85,Strong,High Financial Leverage
19,"22ND CENTURY GROUP, INC.",2024.0,75,Moderate,Low Profitability

In [33]:
# ============================================
# FINANCIAL GUIDANCE GENERATION
# ============================================

def generate_guidance(row):

    guidance = []

    # Revenue
    revenue_growth = row.get("revenue_growth_pct")

    if pd.notna(revenue_growth):
        if revenue_growth > 10:
            guidance.append("Strong revenue growth")
        elif revenue_growth > 0:
            guidance.append("Revenue is growing moderately")
        else:
            guidance.append("Revenue decline requires attention")

    # Net income
    income_growth = row.get("net_income_growth_pct")

    if pd.notna(income_growth):
        if income_growth > 10:
            guidance.append("Profitability is improving")
        elif income_growth < 0:
            guidance.append("Profitability is declining")

    # EPS
    eps_growth = row.get("eps_diluted_growth_pct")

    if pd.notna(eps_growth):
        if eps_growth > 0:
            guidance.append("EPS shows positive momentum")
        else:
            guidance.append("EPS decline should be monitored")

    # Margin
    margin = row.get("net_profit_margin")

    if pd.notna(margin):
        if margin < 5:
            guidance.append("Improve cost efficiency and margins")

    # Leverage
    leverage = row.get("liability_asset_ratio")

    if pd.notna(leverage):
        if leverage > 0.75:
            guidance.append("Monitor debt and financial leverage")

    # Cash
    cash_ratio = row.get("cash_asset_ratio")

    if pd.notna(cash_ratio):
        if cash_ratio < 0.05:
            guidance.append("Strengthen liquidity position")

    if not guidance:
        return "Financial position appears stable"

    return "; ".join(guidance)


financial_wide["financial_guidance"] = (
    financial_wide.apply(generate_guidance, axis=1)
)


display(
    financial_wide[
        [
            "name",
            "year",
            "financial_health_score",
            "financial_health",
            "risk_flags",
            "financial_guidance"
        ]
    ].head(20)
)

,name,year,financial_health_score,financial_health,risk_flags,financial_guidance
0,1 800 FLOWERS COM INC,2024.0,75,Moderate,Low Profitability,Improve cost efficiency and margins
1,1 800 FLOWERS COM INC,2025.0,55,Weak,"Revenue Decline, Low Profitability",Revenue decline requires attention; Profitabil...
2,"10X GENOMICS, INC.",2024.0,75,Moderate,Low Profitability,Improve cost efficiency and margins
3,"10X GENOMICS, INC.",2025.0,40,Weak,"Net Income Decline, EPS Decline, Low Profitabi...",Revenue is growing moderately; Profitability i...
4,1606 CORP.,2024.0,85,Strong,High Financial Leverage,Monitor debt and financial leverage
5,1606 CORP.,2025.0,50,Weak,"Net Income Decline, EPS Decline, High Financia...",Profitability is declining; EPS decline should...
6,1847 HOLDINGS LLC,2024.0,100,Strong,No Major Risk,Financial position appears stable
7,1847 HOLDINGS LLC,2025.0,85,Strong,EPS Decline,Strong revenue growth; Profitability is improv...
8,1RT ACQUISITION CORP.,2024.0,85,Strong,High Financial Leverage,Monitor debt and financial leverage
9,1RT ACQUISITION CORP.,2025.0,100,Strong,Low Cash Position,Strengthen liquidity position
10,1ST FRANKLIN FINANCIAL CORP,2024.0,90,Strong,"Low Profitability, Low Cash Position",Improve cost efficiency and margins; Strengthe...
11,1ST FRANKLIN FINANCIAL CORP,2025.0,100,Strong,Low Cash Position,Strong revenue growth; Profitability is improv...
12,1ST SOURCE CORP,2024.0,75,Moderate,Low Profitability,Improve cost efficiency and margins
13,1ST SOURCE CORP,2025.0,35,Critical,"Revenue Decline, Net Income Decline, Low Profi...",Revenue decline requires attention; Profitabil...
14,"1STDIBS.COM, INC.",2024.0,75,Moderate,Low Profitability,Improve cost efficiency and margins
15,"1STDIBS.COM, INC.",2025.0,40,Weak,"Net Income Decline, EPS Decline, Low Profitabi...",Revenue is growing moderately; Profitability i...
16,21SHARES ETHEREUM ETF,2024.0,100,Strong,No Major Risk,Financial position appears stable
17,21SHARES ETHEREUM ETF,2025.0,80,Strong,Net Income Decline,Profitability is declining
18,21SHARES SOLANA ETF,2025.0,85,Strong,High Financial Leverage,Monitor debt and financial leverage
19,"22ND CENTURY GROUP, INC.",2024.0,75,Moderate,Low Profitability,Improve cost efficiency and margins

In [35]:
!pip install hf_transfer -q

import os
os.environ["HF_HUB_ENABLE_HF_TRANSFER"] = "1"

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

MODEL_NAME = "sshleifer/distilbart-cnn-12-6"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
bart_model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_NAME)

print("BART loaded successfully!")

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: C:\Users\SARATH CHANDRA G\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

Loading weights:   0%|          | 0/358 [00:00<?, ?it/s]

BART loaded successfully!

In [36]:
def bart_summarize(text):

    inputs = tokenizer(
        text,
        return_tensors="pt",
        max_length=1024,
        truncation=True
    )

    summary_ids = bart_model.generate(
        inputs["input_ids"],
        max_length=100,
        min_length=30,
        num_beams=4,
        early_stopping=True
    )

    return tokenizer.decode(
        summary_ids[0],
        skip_special_tokens=True
    )

In [37]:
def create_financial_text(row):

    text = f"""
    Company: {row.get('name', 'Unknown')}.
    Revenue growth: {row.get('revenue_growth_pct', 'N/A')} percent.
    Net income growth: {row.get('net_income_growth_pct', 'N/A')} percent.
    EPS growth: {row.get('eps_diluted_growth_pct', 'N/A')} percent.
    Net profit margin: {row.get('net_profit_margin', 'N/A')} percent.
    Financial health score: {row.get('financial_health_score', 'N/A')} out of 100.
    Financial health: {row.get('financial_health', 'N/A')}.
    Identified risks: {row.get('risk_flags', 'None')}.
    Guidance: {row.get('financial_guidance', 'None')}.
    """

    return " ".join(text.split())

In [39]:
# Keep the financial text
financial_wide["financial_text"] = financial_wide.apply(
    create_financial_text,
    axis=1
)

# No BART
financial_wide["bart_summary"] = financial_wide["financial_text"]

display(
    financial_wide[
        ["name", "year", "financial_text"]
    ].head(10)
)

,name,year,financial_text
0,1 800 FLOWERS COM INC,2024.0,Company: 1 800 FLOWERS COM INC. Revenue growth...
1,1 800 FLOWERS COM INC,2025.0,Company: 1 800 FLOWERS COM INC. Revenue growth...
2,"10X GENOMICS, INC.",2024.0,"Company: 10X GENOMICS, INC.. Revenue growth: n..."
3,"10X GENOMICS, INC.",2025.0,"Company: 10X GENOMICS, INC.. Revenue growth: 7..."
4,1606 CORP.,2024.0,Company: 1606 CORP.. Revenue growth: nan perce...
5,1606 CORP.,2025.0,Company: 1606 CORP.. Revenue growth: nan perce...
6,1847 HOLDINGS LLC,2024.0,Company: 1847 HOLDINGS LLC. Revenue growth: na...
7,1847 HOLDINGS LLC,2025.0,Company: 1847 HOLDINGS LLC. Revenue growth: 38...
8,1RT ACQUISITION CORP.,2024.0,Company: 1RT ACQUISITION CORP.. Revenue growth...
9,1RT ACQUISITION CORP.,2025.0,Company: 1RT ACQUISITION CORP.. Revenue growth...

In [41]:
# ============================================
# BART SUMMARIZATION FUNCTION
# ============================================

def bart_summarize(text):

    inputs = tokenizer(
        text,
        return_tensors="pt",
        max_length=1024,
        truncation=True
    )

    summary_ids = bart_model.generate(
        inputs["input_ids"],
        max_length=100,
        min_length=30,
        num_beams=4,
        early_stopping=True
    )

    return tokenizer.decode(
        summary_ids[0],
        skip_special_tokens=True
    )

In [42]:
display(
    financial_wide[
        [
            "name",
            "year",
            "financial_health",
            "risk_flags",
            "financial_guidance",
            "bart_summary"
        ]
    ].head(10)
)

,name,year,financial_health,risk_flags,financial_guidance,bart_summary
0,1 800 FLOWERS COM INC,2024.0,Moderate,Low Profitability,Improve cost efficiency and margins,Company: 1 800 FLOWERS COM INC. Revenue growth...
1,1 800 FLOWERS COM INC,2025.0,Weak,"Revenue Decline, Low Profitability",Revenue decline requires attention; Profitabil...,Company: 1 800 FLOWERS COM INC. Revenue growth...
2,"10X GENOMICS, INC.",2024.0,Moderate,Low Profitability,Improve cost efficiency and margins,"Company: 10X GENOMICS, INC.. Revenue growth: n..."
3,"10X GENOMICS, INC.",2025.0,Weak,"Net Income Decline, EPS Decline, Low Profitabi...",Revenue is growing moderately; Profitability i...,"Company: 10X GENOMICS, INC.. Revenue growth: 7..."
4,1606 CORP.,2024.0,Strong,High Financial Leverage,Monitor debt and financial leverage,Company: 1606 CORP.. Revenue growth: nan perce...
5,1606 CORP.,2025.0,Weak,"Net Income Decline, EPS Decline, High Financia...",Profitability is declining; EPS decline should...,Company: 1606 CORP.. Revenue growth: nan perce...
6,1847 HOLDINGS LLC,2024.0,Strong,No Major Risk,Financial position appears stable,Company: 1847 HOLDINGS LLC. Revenue growth: na...
7,1847 HOLDINGS LLC,2025.0,Strong,EPS Decline,Strong revenue growth; Profitability is improv...,Company: 1847 HOLDINGS LLC. Revenue growth: 38...
8,1RT ACQUISITION CORP.,2024.0,Strong,High Financial Leverage,Monitor debt and financial leverage,Company: 1RT ACQUISITION CORP.. Revenue growth...
9,1RT ACQUISITION CORP.,2025.0,Strong,Low Cash Position,Strengthen liquidity position,Company: 1RT ACQUISITION CORP.. Revenue growth...

In [43]:
# ============================================
# FINAL STRUCTURED FINANCIAL DATASET
# ============================================

final_columns = [
    "name",
    "cik",
    "year",

    # Financial metrics
    "revenue",
    "net_income",
    "operating_income",
    "gross_profit",
    "assets",
    "liabilities",
    "cash",
    "eps_diluted",
    "operating_cash_flow",

    # Ratios
    "net_profit_margin",
    "operating_margin",
    "gross_margin",
    "liability_asset_ratio",
    "cash_asset_ratio",

    # Growth
    "revenue_growth_pct",
    "net_income_growth_pct",
    "operating_income_growth_pct",
    "gross_profit_growth_pct",
    "assets_growth_pct",
    "liabilities_growth_pct",
    "cash_growth_pct",
    "eps_diluted_growth_pct",

    # Analytics
    "financial_health_score",
    "financial_health",
    "risk_flags",
    "financial_guidance",
    "bart_summary"
]

# Keep only columns that actually exist
final_columns = [
    col for col in final_columns
    if col in financial_wide.columns
]

financial_final = financial_wide[final_columns].copy()

print("Final dataset shape:", financial_final.shape)

display(financial_final.head(10))

Final dataset shape: (11515, 29)

,name,year,revenue,net_income,operating_income,gross_profit,assets,liabilities,cash,eps_diluted,...,gross_profit_growth_pct,assets_growth_pct,liabilities_growth_pct,cash_growth_pct,eps_diluted_growth_pct,financial_health_score,financial_health,risk_flags,financial_guidance,bart_summary
0,1 800 FLOWERS COM INC,2024.0,242.090000,-34.190000,-46.981000,92.319,29.237000,-8.806000,NaN,-5.300000e-07,...,NaN,NaN,NaN,NaN,NaN,75,Moderate,Low Profitability,Improve cost efficiency and margins,Company: 1 800 FLOWERS COM INC. Revenue growth...
1,1 800 FLOWERS COM INC,2025.0,215.200000,-52.957000,-50.513000,76.762,772.617000,109.887000,46.502000,-8.300000e-07,...,-16.851352,2542.600130,-1347.865092,NaN,56.603774,55,Weak,"Revenue Decline, Low Profitability",Revenue decline requires attention; Profitabil...,Company: 1 800 FLOWERS COM INC. Revenue growth...
2,"10X GENOMICS, INC.",2024.0,45.261000,-59.949000,-41.485000,106.393,918.636000,41.165000,NaN,-3.000000e-07,...,NaN,NaN,NaN,NaN,NaN,75,Moderate,Low Profitability,Improve cost efficiency and margins,"Company: 10X GENOMICS, INC.. Revenue growth: n..."
3,"10X GENOMICS, INC.",2025.0,48.695000,-34.358000,-32.242000,100.307,1027.361000,35.766000,NaN,-2.200000e-07,...,-5.720301,11.835482,-13.115511,NaN,-26.666667,40,Weak,"Net Income Decline, EPS Decline, Low Profitabi...",Revenue is growing moderately; Profitability i...,"Company: 10X GENOMICS, INC.. Revenue growth: 7..."
4,1606 CORP.,2024.0,0.000000,-3.569636,-3.246179,0.000,0.010140,0.499231,NaN,-7.000000e-08,...,NaN,NaN,NaN,NaN,NaN,85,Strong,High Financial Leverage,Monitor debt and financial leverage,Company: 1606 CORP.. Revenue growth: nan perce...
5,1606 CORP.,2025.0,0.000000,-0.384516,-0.111446,0.000,0.014602,0.604106,NaN,0.000000e+00,...,NaN,44.003945,21.007309,NaN,-100.000000,50,Weak,"Net Income Decline, EPS Decline, High Financia...",Profitability is declining; EPS decline should...,Company: 1606 CORP.. Revenue growth: nan perce...
6,1847 HOLDINGS LLC,2024.0,1.425247,2.813784,-3.280309,NaN,33.647738,5.853307,2.457086,1.680000e-05,...,NaN,NaN,NaN,NaN,NaN,100,Strong,No Major Risk,Financial position appears stable,Company: 1847 HOLDINGS LLC. Revenue growth: na...
7,1847 HOLDINGS LLC,2025.0,6.897848,32.280122,2.628258,NaN,35.911825,13.098911,2.189759,9.000000e-08,...,NaN,6.728794,123.786502,-10.879839,-99.464286,85,Strong,EPS Decline,Strong revenue growth; Profitability is improv...,Company: 1847 HOLDINGS LLC. Revenue growth: 38...
8,1RT ACQUISITION CORP.,2024.0,NaN,NaN,NaN,NaN,0.143423,0.138355,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,85,Strong,High Financial Leverage,Monitor debt and financial leverage,Company: 1RT ACQUISITION CORP.. Revenue growth...
9,1RT ACQUISITION CORP.,2025.0,NaN,-0.031000,-0.285197,NaN,175.113471,0.204278,0.741229,7.000000e-08,...,NaN,121995.808204,47.647718,NaN,NaN,100,Strong,Low Cash Position,Strengthen liquidity position,Company: 1RT ACQUISITION CORP.. Revenue growth...

In [46]:
# ============================================================
# SAVE CHATBOT-REQUIRED OUTPUTS
# ============================================================

import os
import json

# Use your existing SEC dataset path
CHATBOT_DIR = os.path.join(path, "chatbot_data")

os.makedirs(CHATBOT_DIR, exist_ok=True)

print("Saving chatbot data to:")
print(CHATBOT_DIR)


# ------------------------------------------------------------
# 1. CLEAN RAW DATA
# ------------------------------------------------------------

num.to_csv(
    os.path.join(CHATBOT_DIR, "clean_num.csv"),
    index=False
)

sub.to_csv(
    os.path.join(CHATBOT_DIR, "clean_sub.csv"),
    index=False
)

tag.to_csv(
    os.path.join(CHATBOT_DIR, "tag_data.csv"),
    index=False
)


# ------------------------------------------------------------
# 2. IMPORTANT PROCESSED DATA
# ------------------------------------------------------------

if "financial" in globals():
    financial.to_csv(
        os.path.join(CHATBOT_DIR, "financial_merged.csv"),
        index=False
    )

if "metrics_long" in globals():
    metrics_long.to_csv(
        os.path.join(CHATBOT_DIR, "metrics_long.csv"),
        index=False
    )

if "financial_wide" in globals():
    financial_wide.to_csv(
        os.path.join(CHATBOT_DIR, "financial_wide.csv"),
        index=False
    )

if "financial_final" in globals():
    financial_final.to_csv(
        os.path.join(CHATBOT_DIR, "financial_final.csv"),
        index=False
    )


# ------------------------------------------------------------
# 3. SAVE INDIVIDUAL FINANCIAL METRICS
# ------------------------------------------------------------

metric_files = {
    "revenue": "revenue_df",
    "net_income": "net_income_df",
    "operating_income": "operating_income_df",
    "gross_profit": "gross_profit_df",
    "assets": "assets_df",
    "liabilities": "liabilities_df",
    "cash": "cash_df",
    "eps": "eps_df",
    "operating_cash_flow": "ocf_df"
}

for filename, variable_name in metric_files.items():

    if variable_name in globals():

        df = globals()[variable_name]

        df.to_csv(
            os.path.join(
                CHATBOT_DIR,
                filename + "_data.csv"
            ),
            index=False
        )


# ------------------------------------------------------------
# 4. SAVE COMPANY INFORMATION
# ------------------------------------------------------------

if "TARGET_COMPANIES" in globals():

    with open(
        os.path.join(CHATBOT_DIR, "target_companies.json"),
        "w"
    ) as f:

        json.dump(
            TARGET_COMPANIES,
            f,
            indent=4
        )


# ------------------------------------------------------------
# 5. SAVE METRIC DEFINITIONS
# ------------------------------------------------------------

if "METRIC_TAGS" in globals():

    with open(
        os.path.join(CHATBOT_DIR, "metric_tags.json"),
        "w"
    ) as f:

        json.dump(
            METRIC_TAGS,
            f,
            indent=4
        )


# ------------------------------------------------------------
# 6. SHOW WHAT WAS SAVED
# ------------------------------------------------------------

print("\n============================================")
print("CHATBOT DATA SAVED SUCCESSFULLY")
print("============================================")

for file in sorted(os.listdir(CHATBOT_DIR)):
    print("✓", file)

print("\nFolder:")
print(CHATBOT_DIR)

Saving chatbot data to:
C:\Users\SARATH CHANDRA G\Downloads\2025q4\chatbot_data

============================================
CHATBOT DATA SAVED SUCCESSFULLY
============================================
✓ assets_data.csv
✓ cash_data.csv
✓ clean_num.csv
✓ clean_sub.csv
✓ eps_data.csv
✓ financial_final.csv
✓ financial_merged.csv
✓ financial_wide.csv
✓ gross_profit_data.csv
✓ liabilities_data.csv
✓ metric_tags.json
✓ metrics_long.csv
✓ net_income_data.csv
✓ operating_cash_flow_data.csv
✓ operating_income_data.csv
✓ revenue_data.csv
✓ tag_data.csv
✓ target_companies.json

Folder:
C:\Users\SARATH CHANDRA G\Downloads\2025q4\chatbot_data

In [47]:
# ============================================================
# CREATE FINAL CHATBOT KNOWLEDGE FILE
# ============================================================

import json
import pandas as pd
import os

chatbot_records = []

# Use the final processed dataset
if "financial_final" in globals():

    df = financial_final.copy()

elif "financial_wide" in globals():

    df = financial_wide.copy()

else:

    raise ValueError(
        "financial_final or financial_wide is not available."
    )


# Convert every row into a chatbot-readable record
for _, row in df.iterrows():

    record = {}

    for column in df.columns:

        value = row[column]

        # Convert pandas/NumPy values to JSON-safe values
        if pd.isna(value):
            value = None

        elif hasattr(value, "item"):
            value = value.item()

        elif isinstance(value, (pd.Timestamp,)):
            value = str(value)

        else:
            value = str(value) if not isinstance(
                value,
                (int, float, bool)
            ) else value

        record[column] = value

    chatbot_records.append(record)


# Save JSON
json_path = os.path.join(
    CHATBOT_DIR,
    "chatbot_knowledge.json"
)

with open(
    json_path,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        chatbot_records,
        f,
        indent=2,
        ensure_ascii=False
    )


print("============================================")
print("CHATBOT KNOWLEDGE CREATED")
print("============================================")
print("Records:", len(chatbot_records))
print("File:", json_path)

============================================
CHATBOT KNOWLEDGE CREATED
============================================
Records: 11515
File: C:\Users\SARATH CHANDRA G\Downloads\2025q4\chatbot_data\chatbot_knowledge.json